# Generated by Django 6.0.4 on 2026-04-24 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0004_task_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='due_date',
        ),
    ]
